using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;

using AwesomeAssertions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Nota.CodeAnalysis.Analysers.Test;

public class OperatorPlacementAnalyserTests
{
    /// <summary>
    /// Runs NOTA0002 over <paramref name="body"/>, placed inside a method, and returns the operators it
    /// reported.
    /// </summary>
    internal static async Task<IReadOnlyList<string>> ReportedOperatorsAsync(string body)
    {
        IReadOnlyList<Diagnostic> diagnostics = await DiagnosticsAsync(Wrap(body));

        return diagnostics.Select(d => d.Location.SourceTree!.GetText().ToString(d.Location.SourceSpan)).ToList();
    }

    internal static async Task<IReadOnlyList<Diagnostic>> DiagnosticsAsync(string source)
    {
        SyntaxTree tree = CSharpSyntaxTree.ParseText(source, path: "Test.cs");
        CSharpCompilation compilation = CSharpCompilation.Create("Test", [tree]);
        ImmutableArray<Diagnostic> diagnostics = await compilation.WithAnalyzers([new OperatorPlacementAnalyser()])
                                                                  .GetAnalyzerDiagnosticsAsync(TestContext.Current.CancellationToken);

        return diagnostics.Where(d => d.Id == OperatorPlacementAnalyser.DiagnosticId).ToList();
    }

    internal static string Wrap(string body)
    {
        return "class C\n{\n    object M(bool a, bool b, int x, int y, string? s, object o)\n    {\n" + body + "\n    }\n}\n";
    }

    [Theory]
    [InlineData("return a\n    && b;", "&&")]
    [InlineData("return a\n    || b;", "||")]
    [InlineData("return x\n    + y;", "+")]
    [InlineData("return x\n    - y;", "-")]
    [InlineData("return x\n    * y;", "*")]
    [InlineData("return x\n    | y;", "|")]
    [InlineData("return x\n    != y;", "!=")]
    [InlineData("return x\n    < y;", "<")]
    [InlineData("return s\n    ?? \"\";", "??")]
    [InlineData("return o\n    as string;", "as")]
    [InlineData("return o\n    is int;", "is")]
    [InlineData("return o\n    is int i;", "is")]
    [InlineData("return o is 1\n    or 2;", "or")]
    [InlineData("return o is not null\n    and not 2;", "and")]
    public async Task ReportsAnOperatorThatLeadsItsLine(string body, string op)
    {
        IReadOnlyList<string> reported = await ReportedOperatorsAsync(body);

        reported.Should().Equal(op);
    }

    [Fact]
    public async Task ReportsBothHalvesOfAConditional()
    {
        IReadOnlyList<string> reported = await ReportedOperatorsAsync("return a\n    ? x\n    : y;");

        reported.Should().Equal("?", ":");
    }

    [Fact]
    public async Task ReportsEachOperatorOfAChain()
    {
        IReadOnlyList<string> reported = await ReportedOperatorsAsync("return a\n    && b\n    && a\n    || b;");

        reported.Should().HaveCount(3);
    }

    [Theory]
    [InlineData("return a &&\n    b;")]
    [InlineData("return a ?\n    x :\n    y;")]
    [InlineData("return o is 1 or\n    2;")]
    [InlineData("return a && b;")]
    [InlineData("return a ? x : y;")]
    [InlineData("return a\n    .ToString();")]
    [InlineData("System.Func<int> f = ()\n    => 1;\nreturn f;")]
    [InlineData("return @\"x\n    && y\";")]
    [InlineData("// a\n// && b\nreturn a;")]
    public async Task LeavesEverythingElse(string body)
    {
        IReadOnlyList<string> reported = await ReportedOperatorsAsync(body);

        reported.Should().BeEmpty();
    }

    /// <summary>SA1128 wants a constructor initializer on its own line, and this must not argue.</summary>
    [Fact]
    public async Task LeavesAConstructorInitializerAndABaseList()
    {
        const string source = "class B\n{\n    public B(int x)\n    {\n    }\n}\n\nclass D\n    : B\n{\n    public D()\n        : base(1)\n    {\n    }\n}\n";

        IReadOnlyList<Diagnostic> diagnostics = await DiagnosticsAsync(source);

        diagnostics.Should().BeEmpty();
    }

    [Fact]
    public async Task LeavesGeneratedCode()
    {
        const string source = "// <auto-generated />\nclass C\n{\n    bool M(bool a, bool b)\n    {\n        return a\n            && b;\n    }\n}\n";

        IReadOnlyList<Diagnostic> diagnostics = await DiagnosticsAsync(source);

        diagnostics.Should().BeEmpty();
    }

    [Fact]
    public async Task ReportsAtTheOperator()
    {
        IReadOnlyList<Diagnostic> diagnostics = await DiagnosticsAsync(Wrap("return a\n    && b;"));

        Diagnostic diagnostic = diagnostics.Should().ContainSingle().Subject;
        diagnostic.Location.GetLineSpan().StartLinePosition.Should().Be(new Microsoft.CodeAnalysis.Text.LinePosition(5, 4));
        diagnostic.GetMessage(System.Globalization.CultureInfo.InvariantCulture).Should().StartWith("'&&' leads its line");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Warning);
    }
}
